[tool.poetry]
name = "openai-modeler"
version = "0.0.1"
description = "ToDO"

license = "MIT"
authors = ["Mislav Jaksic <jaksicmislav@gmail.com>"]
maintainers = []
readme = "README.md"

homepage = "https://github.com/MislavJaksic/OpenAIModeler"
repository = "https://github.com/MislavJaksic/OpenAIModeler"
documentation = "https://github.com/MislavJaksic/OpenAIModeler"

keywords = []

classifiers = []

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.2"
loguru = "^0.7.0"
openai = "^0.27.4"

[tool.poetry.dev-dependencies]
pytest-cov = "^4.0.0"
pytest = "^7.3.0"
pytest-asyncio = "^0.21.0"
pytest-integration = "0.2.3"
Sphinx = "^5.0.0"
black = "^23.3.0"
mypy = "^1.2.0"

[tool.poetry.scripts]
openai-modeler = "openai_modeler.runner:run"

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true
# plugins = pydantic.mypy

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = "tests"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
